### ISSUE TITLE
Working with 2.0.4?

### ISSUE THREAD

**Issue by grasdaggel** [shockwavemk/magento2-module-mail#4]
We want to use your module on our shops, but they are running on Mage 2.0.4. 

Any ideas if your module works with this version?

**Comment by shockwavemk** [comment]
I think it should work, cause i'm working on it since Mage 2 beta.
You should install not only the mail module standalone. You will need additionally one of these:
- https://github.com/shockwavemk/magento2-module-mail-smtp
- https://github.com/shockwave-design/magento2-module-mail-mailgun (non-free commercial usage)
